### PR TITLE
[WIP] Allow accessing binary from `vendor/bin`

### PR DESCRIPTION
**Pull request by jadb**
Refs #1

I am trying to see if there is a way I can get the binary working.

### CODE REVIEW

**Comment by jwage** [comment]
I think before this is possible we have to have a better/different way for phpchunkit to be configured. Right now the configuration is in the bin file.

**Comment by jwage** [comment]
It could maybe be done by introducing a phpchunkit.xml file that the configuration is read from which would allow you to configure everything and define what to use for the listener callbacks for sandbox preparation, database creation and sandbox cleanup. Then the bin/phpchunkit would be the same for every implementation.

**Comment by jwage** [comment]
Take a look at #3. This is what I think we should do. Something like that.

**Comment by jadb** [comment]
Closing in favour of #3

**Pull request closed without merging**
